[package]
name = "mandelbrot_cl"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mandelbrot_calculator = { path = "../mandelbrot_calculator_rust", version = "0.1.0" }
termion = "2.0.1"
